# Generated by Django 3.1.1 on 2022-06-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
