# Generated by Django 3.1.1 on 2022-06-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220627_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
