# Generated by Django 3.1.1 on 2022-07-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_book_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.BooleanField(default=False),
        ),
    ]
