# Generated by Django 3.1.1 on 2022-07-15 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0010_auto_20220715_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(related_name='discussion_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
