# Generated by Django 3.1.1 on 2022-07-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220715_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='likes',
        ),
    ]
