# Generated by Django 3.1.1 on 2022-07-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_message_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
